FROM golang:1.12-alpine as build

WORKDIR /app

COPY /app /app

RUN apk update && \
    apk add --no-cache git && \
    go get github.com/go-sql-driver/mysql

FROM alpine

WORKDIR /app

COPY --from=build /app .

RUN addgroup go \
    && adduser -D -G go go \
    && chown -R go:go /app

CMD ["./app"]